version: '3.8'
services:
  mongodb-service:
    image: mongo:5.0
    ports:
      - ${DB_PORT}:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_ADMIN_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_ADMIN_PASSWORD}
  mongo-express-service:
    image: mongo-express:0.54.0
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${DB_ADMIN_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${DB_ADMIN_USERNAME}
      - ME_CONFIG_MONGODB_SERVER=${DB_HOST} # hostname is also used as mongodb container name
  app:
    image: sample-node-express-docker-app:1.0.0
    ports:
      - 3000:3000
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_ADMIN_USERNAME=${DB_ADMIN_USERNAME}
      - DB_ADMIN_PASSWORD=${DB_ADMIN_PASSWORD}
      - DB_NAME=${DB_NAME}
